### ISSUE TITLE
No file folder error

### ISSUE THREAD

**Issue by Xeladem** [joviaux/pygnata#1]
There is a "[ERROR]  UnknownError: 'NoneType' object is not iterable" when a folder is empty in the .pyg file.

For exemple:

``` yaml
    - static:
      - img:
      - js:
        - main.js
```

The creation of the "img" folder will raise an exception.
